#!/usr/bin/env python3
"""Generate LaTeX interaction figures from interaction report snapshots."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


REPORT = Path("reports/lobby-capture-interactions.csv")
OUTPUT = Path("paper/figures/interaction_tradeoffs.tex")


ROWS = {
    "interaction-enforcement-disclosure-0-35-0-35": "Low enforcement/disclosure",
    "interaction-enforcement-disclosure-1-25-1-25": "High enforcement/disclosure",
    "interaction-financing-evasion-1-25-0-90": "High financing/high evasion",
    "interaction-cooling-1-25-revolving-door": "Cooling high/revolving door",
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, default=REPORT)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()

    rows = select_rows(read_rows(args.report))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(rows, args.report), encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as source:
        return list(csv.DictReader(source))


def select_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    indexed = {row["scenarioKey"]: row for row in rows}
    missing = [key for key in ROWS if key not in indexed]
    if missing:
        raise SystemExit("Missing interaction rows: " + ", ".join(missing))
    return [indexed[key] for key in ROWS]


def render(rows: list[dict[str, str]], report: Path) -> str:
    lines = [
        f"% Generated by scripts/generate-interaction-figures.py; source={report}",
        "\\begin{figure}[h]",
        "\\centering",
        "\\scriptsize",
        "\\begin{tabular}{@{}lcccc@{}}",
        "\\toprule",
        "Scenario & Hidden influence & Influence preserved & Net transparency & Comment uptake \\\\",
        "\\midrule",
    ]
    for row in rows:
        label = ROWS[row["scenarioKey"]]
        lines.append(
            " & ".join(
                [
                    escape(label),
                    bar(row["hiddenInfluenceShare"]),
                    bar(row["influencePreservationRate"]),
                    signed(row["netTransparencyGain"]),
                    value(row["commentSubstantiveUptake"]),
                ]
            )
            + " \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Interaction tradeoffs. Bars show the relative magnitude of hidden influence and preserved influence after reforms bind.}",
            "\\label{fig:interaction-tradeoffs}",
            "\\end{figure}",
            "",
        ]
    )
    return "\n".join(lines)


def bar(raw: str) -> str:
    numeric = float(raw)
    width = max(0.0, min(8.0, numeric * 8.0))
    return f"\\rule{{{width:.2f}em}}{{0.7ex}} {numeric:.4f}"


def signed(raw: str) -> str:
    numeric = float(raw)
    return f"{numeric:+.4f}"


def value(raw: str) -> str:
    return f"{float(raw):.4f}"


def escape(value: str) -> str:
    return value.replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")


if __name__ == "__main__":
    raise SystemExit(main())
