#!/usr/bin/env sh
set -eu

tmpdir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmpdir"
}
trap cleanup EXIT

python3 scripts/normalize-calibration.py lda data/fixtures/normalized-lda-lobbying.csv "$tmpdir/lda.csv" >/dev/null
python3 scripts/normalize-calibration.py fec data/fixtures/normalized-fec-campaign-finance.csv "$tmpdir/fec.csv" >/dev/null
python3 scripts/normalize-calibration.py intermediary data/fixtures/normalized-intermediaries.csv "$tmpdir/intermediaries.csv" >/dev/null
python3 scripts/normalize-calibration.py usaspending-actions data/fixtures/normalized-usaspending-procurement-actions.csv "$tmpdir/usaspending-actions.csv" >/dev/null
python3 - "$tmpdir/lda.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 4, len(rows)
assert set(rows[0]) == {"client", "registrant", "issueDomain", "amount", "disclosureLag", "coveredOfficialShare"}
PY
python3 - "$tmpdir/fec.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 5, len(rows)
assert "sourceRecordId" in rows[0], rows[0]
assert "disclosureLag" in rows[0], rows[0]
PY
python3 - "$tmpdir/intermediaries.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 6, len(rows)
assert "donorDisclosure" in rows[0], rows[0]
PY
python3 - "$tmpdir/usaspending-actions.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 5, len(rows)
assert rows[1]["modificationNumber"] == "P00001", rows[1]
assert rows[1]["exPostModification"] == "true", rows[1]
PY

printf 'client,amount\nA,1\n' > "$tmpdir/bad-lda.csv"
if python3 scripts/normalize-calibration.py lda "$tmpdir/bad-lda.csv" "$tmpdir/out.csv" >"$tmpdir/bad.out" 2>"$tmpdir/bad.err"; then
  echo "Expected missing-column normalization failure." >&2
  exit 1
fi
if ! grep -q "missing required fields" "$tmpdir/bad.err"; then
  echo "Missing-column failure did not explain the schema problem." >&2
  cat "$tmpdir/bad.err" >&2
  exit 1
fi

python3 scripts/generate-paper-tables.py --output "$tmpdir/tables" >/dev/null
python3 scripts/generate-interaction-figures.py --skip-pdf-conversion --output "$tmpdir/figures/interaction_tradeoffs.tex" >/dev/null
python3 scripts/extract-source-moments.py --output "$tmpdir/reports" >/dev/null
test -s "$tmpdir/tables/mechanism_comparison.tex"
test -s "$tmpdir/tables/campaign_snapshot.tex"
test -s "$tmpdir/tables/full_campaign_appendix.tex"
test -s "$tmpdir/tables/distortion_decomposition.tex"
test -s "$tmpdir/tables/sensitivity_snapshot.tex"
test -s "$tmpdir/tables/apparent_failure_ranking.tex"
test -s "$tmpdir/tables/substitution_warning_ranking.tex"
test -s "$tmpdir/tables/validation_gap_snapshot.tex"
test -s "$tmpdir/tables/ablation_snapshot.tex"
test -s "$tmpdir/tables/portfolio_snapshot.tex"
test -s "$tmpdir/figures/interaction_tradeoffs.tex"
test -s "$tmpdir/figures/model_architecture.tex"
test -s "$tmpdir/figures/substitution_warning_map.tex"
test -s "$tmpdir/figures/Figure_1_model_architecture.svg"
test -s "$tmpdir/figures/Figure_3_interaction_tradeoffs.svg"
test -s "$tmpdir/figures/Figure_5_substitution_warning_map.svg"
test -s "$tmpdir/reports/source-moments.csv"
grep -q "Generated by scripts/generate-paper-tables.py" "$tmpdir/tables/campaign_snapshot.tex"
grep -q "Generated by scripts/generate-interaction-figures.py" "$tmpdir/figures/interaction_tradeoffs.tex"
grep -q "Figure_1_model_architecture.pdf" "$tmpdir/figures/model_architecture.tex"
grep -q "Figure_3_interaction_tradeoffs.pdf" "$tmpdir/figures/interaction_tradeoffs.tex"
grep -q "Figure_5_substitution_warning_map.pdf" "$tmpdir/figures/substitution_warning_map.tex"
grep -q "tab:first-campaign" "$tmpdir/tables/campaign_snapshot.tex"
grep -q "tab:full-campaign-appendix" "$tmpdir/tables/full_campaign_appendix.tex"
grep -q "tab:distortion-decomposition" "$tmpdir/tables/distortion_decomposition.tex"
grep -q "tab:mechanism-comparison" "$tmpdir/tables/mechanism_comparison.tex"
grep -q "tab:sensitivity" "$tmpdir/tables/sensitivity_snapshot.tex"
grep -q "tab:apparent-failures" "$tmpdir/tables/apparent_failure_ranking.tex"
grep -q "tab:substitution-warnings" "$tmpdir/tables/substitution_warning_ranking.tex"
grep -q "tab:validation-gaps" "$tmpdir/tables/validation_gap_snapshot.tex"
grep -q "tab:ablation" "$tmpdir/tables/ablation_snapshot.tex"
grep -q "tab:portfolio" "$tmpdir/tables/portfolio_snapshot.tex"
grep -q "lobbyingClientTop1Share" "$tmpdir/reports/source-moments.csv"
grep -q "outsideSpendingSourceShare" "$tmpdir/reports/source-moments.csv"
grep -q "publicFinancingRows" "$tmpdir/reports/source-moments.csv"
grep -q "procurementRecipientTop3Share" "$tmpdir/reports/source-moments.csv"
grep -q "procurementActionRows" "$tmpdir/reports/source-moments.csv"
grep -q "procurementBridgeAgencyCount" "$tmpdir/reports/source-moments.csv"
grep -q "procurementAmountWeightedSingleBidShare" "$tmpdir/reports/source-moments.csv"
grep -q "procurementInitialAwardShare" "$tmpdir/reports/source-moments.csv"
grep -q "procurementActionModificationRows" "$tmpdir/reports/source-moments.csv"
grep -q "procurementLimitedCompetitionShare" "$tmpdir/reports/source-moments.csv"
grep -q "revolvingDoorFormerOfficialShare" "$tmpdir/reports/source-moments.csv"
grep -q "intermediaryPoliticalSpendShare" "$tmpdir/reports/source-moments.csv"
python3 scripts/audit-source-panels.py --source-moments "$tmpdir/reports/source-moments.csv" --output "$tmpdir/reports" >/dev/null
test -s "$tmpdir/reports/source-panel-inventory.csv"
grep -q "Direct dark money" "$tmpdir/reports/source-panel-inventory.md"
grep -q "Fixture scaffold?" "$tmpdir/reports/source-panel-inventory.md"
python3 scripts/audit-source-capabilities.py --reports "$tmpdir/reports" --snapshot data/snapshots/2024-env >/dev/null
test -s "$tmpdir/reports/source-capability-audit.csv"
grep -q "snapshotQuality" "$tmpdir/reports/source-capability-audit.csv"
grep -q "sam-contract-awards-action-history" "$tmpdir/reports/source-capability-audit.csv"
python3 scripts/audit-procurement-denominator.py --reports "$tmpdir/reports" --snapshot data/snapshots/2024-env >/dev/null
test -s "$tmpdir/reports/procurement-denominator-audit.csv"
test -s "$tmpdir/reports/procurement-denominator-audit.md"
grep -q "promotionReadiness" "$tmpdir/reports/procurement-denominator-audit.csv"
grep -q "dateSpanDisplay" "$tmpdir/reports/procurement-denominator-audit.csv"
grep -q "sam-contract-awards" "$tmpdir/reports/procurement-denominator-audit.csv"
grep -q "promotion readiness" "$tmpdir/reports/procurement-denominator-audit.md"
python3 scripts/classify-validation-misses.py --validation reports/validation-summary.csv --source-moments "$tmpdir/reports/source-moments.csv" --output "$tmpdir/reports" >/dev/null
python3 scripts/write-procurement-refresh-readiness.py --reports "$tmpdir/reports" --snapshot data/snapshots/2024-env >/dev/null
test -s "$tmpdir/reports/procurement-refresh-readiness.csv"
test -s "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "Procurement Refresh Readiness" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "archived USAspending bulk diagnostics" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "Do not promote partial SAM payloads" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "Calibrated policy-simulation claims remain blocked" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "SAM_CONTRACT_AWARDS_EXTRACT_MODE=1" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "SAM_CONTRACT_AWARDS_OFFSET_STARTS" "$tmpdir/reports/procurement-refresh-readiness.md"

cat > "$tmpdir/sam-export.csv" <<'CSV'
contractId.piid,modification_number,recipientName,contractingDepartmentName,contractingSubtierName,awardOrIDVTypeName,Federal Action Obligation,Recipient UEI,actionDate,extentCompetedName,numberOfOffers,typeOfContractPricingName
68HERH24C0004,0,MANUAL EXPORT CONTRACTOR,ENVIRONMENTAL PROTECTION AGENCY,EPA OFFICE,DEFINITIVE CONTRACT,1250000,EXPORTUEI1234,2024-01-15,FULL AND OPEN COMPETITION,5,FIRM FIXED PRICE
68HERH24C0004,P00004,MANUAL EXPORT CONTRACTOR,ENVIRONMENTAL PROTECTION AGENCY,EPA OFFICE,DEFINITIVE CONTRACT,250000,EXPORTUEI1234,2024-09-15,FULL AND OPEN COMPETITION,5,FIRM FIXED PRICE
CSV
python3 scripts/audit-sam-contract-awards-export.py \
  --input "$tmpdir/sam-export.csv" \
  --reports "$tmpdir/reports" \
  --min-rows 2 \
  --min-awards 1 \
  --min-agencies 1 \
  --min-date-span-days 0 \
  --min-piid-share 1.0 \
  --min-uei-share 1.0 \
  --min-action-date-share 1.0 \
  --min-competition-share 1.0 >/dev/null
test -s "$tmpdir/reports/sam-contract-awards-export-audit.csv"
test -s "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "SAM Contract Awards Export Audit" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "promotion-readiness,candidate" "$tmpdir/reports/sam-contract-awards-export-audit.csv"
grep -q "Modified action share" "$tmpdir/reports/sam-contract-awards-export-audit.md"

python3 scripts/test-source-fetchers.py

printf 'GET https://api.sam.gov/contract-awards/v1/search?api_key=REDACTED failed with HTTP 429: {"code":"900804","message":"Message throttled out","description":"You have exceeded your quota .","nextAccessTime":"2026-Jun-13 00:00:00+0000 UTC"}\n' > "$tmpdir/sam-quota.log"
python3 scripts/classify-source-failure.py sam-contract-awards "$tmpdir/sam-quota.log" --context "mode=0" --fallback-note "fallback=USAspending action rows" > "$tmpdir/sam-quota-status.csv"
python3 - "$tmpdir/sam-quota-status.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source, fieldnames=["source", "status", "notes"]))
assert rows[0]["source"] == "sam-contract-awards", rows[0]
assert rows[0]["status"] == "quota_blocked", rows[0]
assert "2026-Jun-13 00:00:00+0000 UTC" in rows[0]["notes"], rows[0]
assert "fallback=USAspending action rows" in rows[0]["notes"], rows[0]
PY

echo "Normalizer and table-generator tests passed."
