#!/usr/bin/env sh
set -eu

tmpdir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmpdir"
}
trap cleanup EXIT

python3 scripts/normalize-calibration.py lda data/fixtures/normalized-lda-lobbying.csv "$tmpdir/lda.csv" >/dev/null
python3 scripts/normalize-calibration.py fec data/fixtures/normalized-fec-campaign-finance.csv "$tmpdir/fec.csv" >/dev/null
python3 scripts/normalize-calibration.py intermediary data/fixtures/normalized-intermediaries.csv "$tmpdir/intermediaries.csv" >/dev/null
python3 scripts/normalize-calibration.py usaspending-actions data/fixtures/normalized-usaspending-procurement-actions.csv "$tmpdir/usaspending-actions.csv" >/dev/null
python3 - "$tmpdir/lda.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 4, len(rows)
assert set(rows[0]) == {"client", "registrant", "issueDomain", "amount", "disclosureLag", "coveredOfficialShare"}
PY
python3 - "$tmpdir/fec.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 5, len(rows)
assert "sourceRecordId" in rows[0], rows[0]
assert "disclosureLag" in rows[0], rows[0]
PY
python3 - "$tmpdir/intermediaries.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 6, len(rows)
assert "donorDisclosure" in rows[0], rows[0]
PY
python3 - "$tmpdir/usaspending-actions.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 5, len(rows)
assert rows[1]["modificationNumber"] == "P00001", rows[1]
assert rows[1]["exPostModification"] == "true", rows[1]
PY

printf 'client,amount\nA,1\n' > "$tmpdir/bad-lda.csv"
if python3 scripts/normalize-calibration.py lda "$tmpdir/bad-lda.csv" "$tmpdir/out.csv" >"$tmpdir/bad.out" 2>"$tmpdir/bad.err"; then
  echo "Expected missing-column normalization failure." >&2
  exit 1
fi
if ! grep -q "missing required fields" "$tmpdir/bad.err"; then
  echo "Missing-column failure did not explain the schema problem." >&2
  cat "$tmpdir/bad.err" >&2
  exit 1
fi

python3 scripts/generate-paper-tables.py --output "$tmpdir/tables" >/dev/null
python3 scripts/generate-interaction-figures.py --skip-pdf-conversion --output "$tmpdir/figures/interaction_tradeoffs.tex" >/dev/null
python3 scripts/extract-source-moments.py --output "$tmpdir/reports" >/dev/null
test -s "$tmpdir/tables/mechanism_comparison.tex"
test -s "$tmpdir/tables/campaign_snapshot.tex"
test -s "$tmpdir/tables/full_campaign_appendix.tex"
test -s "$tmpdir/tables/distortion_decomposition.tex"
test -s "$tmpdir/tables/sensitivity_snapshot.tex"
test -s "$tmpdir/tables/apparent_failure_ranking.tex"
test -s "$tmpdir/tables/substitution_warning_ranking.tex"
test -s "$tmpdir/tables/validation_gap_snapshot.tex"
test -s "$tmpdir/tables/ablation_snapshot.tex"
test -s "$tmpdir/tables/portfolio_snapshot.tex"
test -s "$tmpdir/figures/interaction_tradeoffs.tex"
test -s "$tmpdir/figures/model_architecture.tex"
test -s "$tmpdir/figures/substitution_warning_map.tex"
test -s "$tmpdir/figures/Figure_1_model_architecture.svg"
test -s "$tmpdir/figures/Figure_3_interaction_tradeoffs.svg"
test -s "$tmpdir/figures/Figure_5_substitution_warning_map.svg"
test -s "$tmpdir/reports/source-moments.csv"
grep -q "Generated by scripts/generate-paper-tables.py" "$tmpdir/tables/campaign_snapshot.tex"
grep -q "Generated by scripts/generate-interaction-figures.py" "$tmpdir/figures/interaction_tradeoffs.tex"
grep -q "Figure_1_model_architecture.pdf" "$tmpdir/figures/model_architecture.tex"
grep -q "Figure_3_interaction_tradeoffs.pdf" "$tmpdir/figures/interaction_tradeoffs.tex"
grep -q "Figure_5_substitution_warning_map.pdf" "$tmpdir/figures/substitution_warning_map.tex"
grep -q "tab:first-campaign" "$tmpdir/tables/campaign_snapshot.tex"
grep -q "tab:full-campaign-appendix" "$tmpdir/tables/full_campaign_appendix.tex"
grep -q "tab:distortion-decomposition" "$tmpdir/tables/distortion_decomposition.tex"
grep -q "tab:mechanism-comparison" "$tmpdir/tables/mechanism_comparison.tex"
grep -q "tab:sensitivity" "$tmpdir/tables/sensitivity_snapshot.tex"
grep -q "tab:apparent-failures" "$tmpdir/tables/apparent_failure_ranking.tex"
grep -q "tab:substitution-warnings" "$tmpdir/tables/substitution_warning_ranking.tex"
grep -q "tab:validation-gaps" "$tmpdir/tables/validation_gap_snapshot.tex"
grep -q "tab:ablation" "$tmpdir/tables/ablation_snapshot.tex"
grep -q "tab:portfolio" "$tmpdir/tables/portfolio_snapshot.tex"
grep -q "lobbyingClientTop1Share" "$tmpdir/reports/source-moments.csv"
grep -q "outsideSpendingSourceShare" "$tmpdir/reports/source-moments.csv"
grep -q "publicFinancingRows" "$tmpdir/reports/source-moments.csv"
grep -q "procurementRecipientTop3Share" "$tmpdir/reports/source-moments.csv"
grep -q "procurementActionRows" "$tmpdir/reports/source-moments.csv"
grep -q "procurementBridgeAgencyCount" "$tmpdir/reports/source-moments.csv"
grep -q "procurementAmountWeightedSingleBidShare" "$tmpdir/reports/source-moments.csv"
grep -q "procurementInitialAwardShare" "$tmpdir/reports/source-moments.csv"
grep -q "procurementActionModificationRows" "$tmpdir/reports/source-moments.csv"
grep -q "procurementLimitedCompetitionShare" "$tmpdir/reports/source-moments.csv"
grep -q "revolvingDoorFormerOfficialShare" "$tmpdir/reports/source-moments.csv"
grep -q "intermediaryPoliticalSpendShare" "$tmpdir/reports/source-moments.csv"
python3 scripts/audit-source-panels.py --source-moments "$tmpdir/reports/source-moments.csv" --output "$tmpdir/reports" >/dev/null
test -s "$tmpdir/reports/source-panel-inventory.csv"
grep -q "Direct dark money" "$tmpdir/reports/source-panel-inventory.md"
grep -q "Fixture scaffold?" "$tmpdir/reports/source-panel-inventory.md"

python3 scripts/test-source-fetchers.py

echo "Normalizer and table-generator tests passed."
