#!/usr/bin/env sh
set -eu

tmpdir="$(mktemp -d)"
repo_root="$(pwd)"
preserve_report() {
  file="$1"
  if [ -f "$file" ]; then
    mkdir -p "$tmpdir/preserved-reports"
    cp "$file" "$tmpdir/preserved-reports/$(basename "$file")"
  fi
}
restore_report() {
  file="$1"
  backup="$tmpdir/preserved-reports/$(basename "$file")"
  if [ -f "$backup" ]; then
    cp "$backup" "$file"
  else
    rm -f "$file"
  fi
}
preserve_report reports/sam-contract-awards-export-audit.csv
preserve_report reports/sam-contract-awards-export-audit.md
cleanup() {
  restore_report reports/sam-contract-awards-export-audit.csv
  restore_report reports/sam-contract-awards-export-audit.md
  rm -rf "$tmpdir"
}
trap cleanup EXIT

mkdir -p "$tmpdir/load-env"
cat > "$tmpdir/load-env/.env" <<'ENV'
PRESET_VALUE=from_env_file
FRESH_VALUE="two words"
export EXPORTED_VALUE=from_export
SAM_CONTRACT_AWARDS_LIVE_URL=https://api.sam.gov/contract-awards/v1/download?api_key=REPLACE_WITH_API_KEY&token=example-token
INVALID-KEY=ignored
ENV
(
  cd "$tmpdir/load-env"
  LOAD_ENV_PATH="$repo_root/scripts/load-env.sh" PRESET_VALUE=from_caller sh -c '
    . "$LOAD_ENV_PATH"
    test "$PRESET_VALUE" = "from_caller"
    test "$FRESH_VALUE" = "two words"
    test "$EXPORTED_VALUE" = "from_export"
    test "$SAM_CONTRACT_AWARDS_LIVE_URL" = "https://api.sam.gov/contract-awards/v1/download?api_key=REPLACE_WITH_API_KEY&token=example-token"
  '
)

python3 scripts/normalize-calibration.py lda data/fixtures/normalized-lda-lobbying.csv "$tmpdir/lda.csv" >/dev/null
python3 scripts/normalize-calibration.py fec data/fixtures/normalized-fec-campaign-finance.csv "$tmpdir/fec.csv" >/dev/null
python3 scripts/normalize-calibration.py intermediary data/fixtures/normalized-intermediaries.csv "$tmpdir/intermediaries.csv" >/dev/null
python3 scripts/normalize-calibration.py usaspending-actions data/fixtures/normalized-usaspending-procurement-actions.csv "$tmpdir/usaspending-actions.csv" >/dev/null
python3 - "$tmpdir/lda.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 4, len(rows)
assert set(rows[0]) == {"client", "registrant", "issueDomain", "amount", "disclosureLag", "coveredOfficialShare"}
PY
python3 - "$tmpdir/fec.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 5, len(rows)
assert "sourceRecordId" in rows[0], rows[0]
assert "disclosureLag" in rows[0], rows[0]
PY
python3 - "$tmpdir/intermediaries.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 6, len(rows)
assert "donorDisclosure" in rows[0], rows[0]
PY
python3 - "$tmpdir/usaspending-actions.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source))
assert len(rows) == 5, len(rows)
assert rows[1]["modificationNumber"] == "P00001", rows[1]
assert rows[1]["exPostModification"] == "true", rows[1]
PY

printf 'client,amount\nA,1\n' > "$tmpdir/bad-lda.csv"
if python3 scripts/normalize-calibration.py lda "$tmpdir/bad-lda.csv" "$tmpdir/out.csv" >"$tmpdir/bad.out" 2>"$tmpdir/bad.err"; then
  echo "Expected missing-column normalization failure." >&2
  exit 1
fi
if ! grep -q "missing required fields" "$tmpdir/bad.err"; then
  echo "Missing-column failure did not explain the schema problem." >&2
  cat "$tmpdir/bad.err" >&2
  exit 1
fi

python3 scripts/generate-paper-tables.py --output "$tmpdir/tables" >/dev/null
python3 scripts/generate-interaction-figures.py --skip-pdf-conversion --output "$tmpdir/figures/interaction_tradeoffs.tex" >/dev/null
python3 scripts/extract-source-moments.py --output "$tmpdir/reports" >/dev/null
test -s "$tmpdir/tables/mechanism_comparison.tex"
test -s "$tmpdir/tables/campaign_snapshot.tex"
test -s "$tmpdir/tables/full_campaign_appendix.tex"
test -s "$tmpdir/tables/distortion_decomposition.tex"
test -s "$tmpdir/tables/sensitivity_snapshot.tex"
test -s "$tmpdir/tables/apparent_failure_ranking.tex"
test -s "$tmpdir/tables/substitution_warning_ranking.tex"
test -s "$tmpdir/tables/validation_gap_snapshot.tex"
test -s "$tmpdir/tables/ablation_snapshot.tex"
test -s "$tmpdir/tables/portfolio_snapshot.tex"
test -s "$tmpdir/figures/interaction_tradeoffs.tex"
test -s "$tmpdir/figures/model_architecture.tex"
test -s "$tmpdir/figures/substitution_warning_map.tex"
test -s "$tmpdir/figures/Figure_1_model_architecture.svg"
test -s "$tmpdir/figures/Figure_3_interaction_tradeoffs.svg"
test -s "$tmpdir/figures/Figure_5_substitution_warning_map.svg"
test -s "$tmpdir/reports/source-moments.csv"
grep -q "Generated by scripts/generate-paper-tables.py" "$tmpdir/tables/campaign_snapshot.tex"
grep -q "Generated by scripts/generate-interaction-figures.py" "$tmpdir/figures/interaction_tradeoffs.tex"
grep -q "Figure_1_model_architecture.pdf" "$tmpdir/figures/model_architecture.tex"
grep -q "Figure_3_interaction_tradeoffs.pdf" "$tmpdir/figures/interaction_tradeoffs.tex"
grep -q "Figure_5_substitution_warning_map.pdf" "$tmpdir/figures/substitution_warning_map.tex"
grep -q "tab:first-campaign" "$tmpdir/tables/campaign_snapshot.tex"
grep -q "tab:full-campaign-appendix" "$tmpdir/tables/full_campaign_appendix.tex"
grep -q "tab:distortion-decomposition" "$tmpdir/tables/distortion_decomposition.tex"
grep -q "tab:mechanism-comparison" "$tmpdir/tables/mechanism_comparison.tex"
grep -q "tab:sensitivity" "$tmpdir/tables/sensitivity_snapshot.tex"
grep -q "tab:apparent-failures" "$tmpdir/tables/apparent_failure_ranking.tex"
grep -q "tab:substitution-warnings" "$tmpdir/tables/substitution_warning_ranking.tex"
grep -q "tab:validation-gaps" "$tmpdir/tables/validation_gap_snapshot.tex"
grep -q "tab:ablation" "$tmpdir/tables/ablation_snapshot.tex"
grep -q "tab:portfolio" "$tmpdir/tables/portfolio_snapshot.tex"
grep -q "lobbyingClientTop1Share" "$tmpdir/reports/source-moments.csv"
grep -q "outsideSpendingSourceShare" "$tmpdir/reports/source-moments.csv"
grep -q "publicFinancingRows" "$tmpdir/reports/source-moments.csv"
grep -q "procurementRecipientTop3Share" "$tmpdir/reports/source-moments.csv"
grep -q "procurementActionRows" "$tmpdir/reports/source-moments.csv"
grep -q "procurementBridgeAgencyCount" "$tmpdir/reports/source-moments.csv"
grep -q "procurementAmountWeightedSingleBidShare" "$tmpdir/reports/source-moments.csv"
grep -q "procurementInitialAwardShare" "$tmpdir/reports/source-moments.csv"
grep -q "procurementActionModificationRows" "$tmpdir/reports/source-moments.csv"
grep -q "procurementLimitedCompetitionShare" "$tmpdir/reports/source-moments.csv"
grep -q "revolvingDoorFormerOfficialShare" "$tmpdir/reports/source-moments.csv"
grep -q "intermediaryPoliticalSpendShare" "$tmpdir/reports/source-moments.csv"
python3 scripts/audit-source-panels.py --source-moments "$tmpdir/reports/source-moments.csv" --output "$tmpdir/reports" >/dev/null
test -s "$tmpdir/reports/source-panel-inventory.csv"
grep -q "Direct dark money" "$tmpdir/reports/source-panel-inventory.md"
grep -q "Fixture scaffold?" "$tmpdir/reports/source-panel-inventory.md"
python3 scripts/audit-source-capabilities.py --reports "$tmpdir/reports" --snapshot data/snapshots/2024-env >/dev/null
test -s "$tmpdir/reports/source-capability-audit.csv"
grep -q "snapshotQuality" "$tmpdir/reports/source-capability-audit.csv"
grep -q "sam-contract-awards-action-history" "$tmpdir/reports/source-capability-audit.csv"
python3 scripts/audit-procurement-denominator.py --reports "$tmpdir/reports" --snapshot data/snapshots/2024-env >/dev/null
test -s "$tmpdir/reports/procurement-denominator-audit.csv"
test -s "$tmpdir/reports/procurement-denominator-audit.md"
grep -q "promotionReadiness" "$tmpdir/reports/procurement-denominator-audit.csv"
grep -q "dateSpanDisplay" "$tmpdir/reports/procurement-denominator-audit.csv"
grep -q "sam-contract-awards" "$tmpdir/reports/procurement-denominator-audit.csv"
grep -q "promotion readiness" "$tmpdir/reports/procurement-denominator-audit.md"
python3 scripts/classify-validation-misses.py --validation reports/validation-summary.csv --source-moments "$tmpdir/reports/source-moments.csv" --output "$tmpdir/reports" >/dev/null
python3 scripts/write-procurement-refresh-readiness.py --reports "$tmpdir/reports" --snapshot data/snapshots/2024-env >/dev/null
test -s "$tmpdir/reports/procurement-refresh-readiness.csv"
test -s "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "Procurement Refresh Readiness" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "archived USAspending bulk diagnostics" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "Do not promote partial SAM payloads" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "calibrated policy-simulation claims remain outside scope" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "SAM_CONTRACT_AWARDS_EXTRACT_MODE=1" "$tmpdir/reports/procurement-refresh-readiness.md"
grep -q "SAM_CONTRACT_AWARDS_OFFSET_STARTS" "$tmpdir/reports/procurement-refresh-readiness.md"

mkdir -p "$tmpdir/source-root/data/calibration/first-wave"
python3 scripts/write-first-wave-source-product-templates.py --root "$tmpdir/source-root" >/dev/null
test -s "$tmpdir/source-root/docs/source-product-templates/first-wave/README.md"
test -s "$tmpdir/source-root/docs/source-product-templates/first-wave/manifest.csv"
test -s "$tmpdir/source-root/docs/source-product-templates/first-wave/substitution-reform-shocks.csv"
test -s "$tmpdir/source-root/docs/source-product-templates/first-wave/meeting-log-channel-note.md"
grep -q "Do not treat these templates as evidence" "$tmpdir/source-root/docs/source-product-templates/first-wave/README.md"
grep -q "cannot satisfy the production source-product audit" "$tmpdir/source-root/docs/source-product-templates/first-wave/manifest.md"
test ! -f "$tmpdir/source-root/data/calibration/first-wave/comment-body-corpus.csv"
python3 - "$tmpdir/source-root/docs/source-product-templates/first-wave/substitution-reform-shocks.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.reader(source))
assert len(rows) == 1, rows
assert rows[0][:3] == ["reformEventId", "eventName", "jurisdiction"], rows[0]
PY
cat > "$tmpdir/source-root/data/calibration/first-wave/substitution-reform-shocks.csv" <<'CSV'
reformEventId,eventName,jurisdiction,policyDomain,reformType,eventDate,treatmentStartDate,affectedActorRule,affectedIssueRule,comparisonRule,sourceUrl,sourceExtractedAt
shock-1,Example disclosure rule,Example State,environment,disclosure,2024-01-01,2024-02-01,covered registrants,ENV issues,matched unaffected actors,https://example.test/reform,2026-06-15
CSV
python3 scripts/audit-first-wave-source-products.py --root "$tmpdir/source-root" --reports "$tmpdir/reports" >/dev/null
test -s "$tmpdir/reports/first-wave-source-products.csv"
test -s "$tmpdir/reports/first-wave-source-products.md"
grep -q "substitution-reform-shocks" "$tmpdir/reports/first-wave-source-products.csv"
grep -q "templatePath" "$tmpdir/reports/first-wave-source-products.csv"
grep -q "substitution-reform-shocks,.*schema_ready" "$tmpdir/reports/first-wave-source-products.csv"
grep -q "sam-fpds-action-history-crosswalk,.*missing_required" "$tmpdir/reports/first-wave-source-products.csv"
grep -q "schema/acquisition gate" "$tmpdir/reports/first-wave-source-products.md"
grep -q "docs/source-product-templates/first-wave/substitution-reform-shocks.csv" "$tmpdir/reports/first-wave-source-products.md"
grep -q "SAM/FPDS action-history export or keyed pull" "$tmpdir/reports/first-wave-source-products.md"
grep -q "canonical actor identifier table" "$tmpdir/reports/first-wave-source-products.md"

cat > "$tmpdir/source-root/data/calibration/first-wave/substitution-reform-shocks.csv" <<'CSV'
reformEventId,eventName,jurisdiction,policyDomain,reformType,eventDate,treatmentStartDate,affectedActorRule,affectedIssueRule,comparisonRule,sourceUrl,sourceExtractedAt
shock-1,TODO,Example State,environment,disclosure,not-a-date,2024-02-01,covered registrants,ENV issues,matched unaffected actors,not-a-url,not-a-date
CSV
python3 scripts/audit-first-wave-source-products.py --root "$tmpdir/source-root" --reports "$tmpdir/reports" >/dev/null
grep -q "qualityIssueCount" "$tmpdir/reports/first-wave-source-products.csv"
grep -q "substitution-reform-shocks,.*schema_quality_issues" "$tmpdir/reports/first-wave-source-products.csv"
grep -q "Products with field-level quality issues" "$tmpdir/reports/first-wave-source-products.md"

cat > "$tmpdir/sam-export.csv" <<'CSV'
contractId.piid,modification_number,recipientName,contractingDepartmentName,contractingSubtierName,awardOrIDVTypeName,Federal Action Obligation,Recipient UEI,actionDate,extentCompetedName,numberOfOffers,typeOfContractPricingName
68HERH24C0004,0,MANUAL EXPORT CONTRACTOR,ENVIRONMENTAL PROTECTION AGENCY,EPA OFFICE,DEFINITIVE CONTRACT,1250000,EXPORTUEI1234,2024-01-15,FULL AND OPEN COMPETITION,5,FIRM FIXED PRICE
68HERH24C0004,P00004,MANUAL EXPORT CONTRACTOR,ENVIRONMENTAL PROTECTION AGENCY,EPA OFFICE,DEFINITIVE CONTRACT,250000,EXPORTUEI1234,2024-09-15,FULL AND OPEN COMPETITION,5,FIRM FIXED PRICE
CSV
python3 scripts/audit-sam-contract-awards-export.py \
  --input "$tmpdir/sam-export.csv" \
  --reports "$tmpdir/reports" \
  --min-rows 2 \
  --min-awards 1 \
  --min-agencies 1 \
  --min-date-span-days 0 \
  --min-piid-share 1.0 \
  --min-uei-share 1.0 \
  --min-action-date-share 1.0 \
  --min-competition-share 1.0 >/dev/null
test -s "$tmpdir/reports/sam-contract-awards-export-audit.csv"
test -s "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "SAM Contract Awards Export Audit" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "promotion-readiness,candidate" "$tmpdir/reports/sam-contract-awards-export-audit.csv"
grep -q "Modified action share" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "Export Shape Diagnostics" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "Next Export Specification" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "Required field families" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "SAM_CONTRACT_AWARDS_LIVE_URL" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "REPLACE_WITH_API_KEY" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "raw-action-date-candidate-share" "$tmpdir/reports/sam-contract-awards-export-audit.csv"

python3 - "$tmpdir/reports/sam-contract-awards-export-audit.csv" "$tmpdir/sam-export.csv" <<'PY'
import importlib.util
import os
from pathlib import Path
import sys

audit_csv = Path(sys.argv[1])
configured_export = Path(sys.argv[2])
spec = importlib.util.spec_from_file_location(
    "external_checklist",
    Path("scripts/write-external-finalization-checklist.py"),
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module.SAM_EXPORT_AUDIT_CSV = audit_csv
os.environ["SAM_CONTRACT_AWARDS_LIVE_CSV"] = str(configured_export)
try:
    row = module.sam_export_audit_row()
finally:
    os.environ.pop("SAM_CONTRACT_AWARDS_LIVE_CSV", None)
assert row["status"] == "ready", row
assert "sourceRows=2" in row["evidence"], row
assert "auditRows=" in row["evidence"], row
assert "rows=18" not in row["evidence"], row
PY

python3 - <<'PY'
import gzip
import importlib.util
from pathlib import Path

spec = importlib.util.spec_from_file_location(
    "fetch_source_data",
    Path("scripts/fetch-source-data.py"),
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

csv_text = """contractId.piid,modification_number,recipientName,contractingDepartmentName,contractingSubtierName,awardOrIDVTypeName,Federal Action Obligation,Recipient UEI,actionDate,extentCompetedName,numberOfOffers,typeOfContractPricingName
68HERH24C0007,P00002,ASYNC EXPORT CONTRACTOR,ENVIRONMENTAL PROTECTION AGENCY,EPA OFFICE,DEFINITIVE CONTRACT,125000,ASYNCUEI1234,2024-06-01,FULL AND OPEN COMPETITION,4,FIRM FIXED PRICE
"""

def fake_download(_url, target):
    target.write_bytes(gzip.compress(csv_text.encode("utf-8")))
    return target

module.download_sam_contract_awards_export_url = fake_download
records = module.sam_contract_awards_extract_records({"token": "fixture"}, "fixture-key", "json")
assert len(records) == 1, records
assert records[0]["piid"] == "68HERH24C0007", records
assert records[0]["modificationNumber"] == "P00002", records
PY

cat > "$tmpdir/sam-solicitation-only-export.csv" <<'CSV'
contractId.piid,modification_number,recipientName,contractingDepartmentName,contractingSubtierName,awardOrIDVTypeName,Recipient UEI,solicitationDate,extentCompetedName,numberOfOffers,typeOfContractPricingName
68HERH24C0004,0,MANUAL EXPORT CONTRACTOR,ENVIRONMENTAL PROTECTION AGENCY,EPA OFFICE,DEFINITIVE CONTRACT,EXPORTUEI1234,2024-01-15,FULL AND OPEN COMPETITION,5,FIRM FIXED PRICE
68HERH24C0005,0,SECOND MANUAL EXPORT CONTRACTOR,ENVIRONMENTAL PROTECTION AGENCY,EPA OFFICE,DEFINITIVE CONTRACT,EXPORTUEI5678,2024-09-15,FULL AND OPEN COMPETITION,3,FIRM FIXED PRICE
CSV
if python3 scripts/audit-sam-contract-awards-export.py \
  --input "$tmpdir/sam-solicitation-only-export.csv" \
  --reports "$tmpdir/reports" \
  --min-rows 2 \
  --min-awards 1 \
  --min-agencies 1 \
  --min-date-span-days 0 \
  --min-piid-share 1.0 \
  --min-uei-share 1.0 \
  --min-action-date-share 1.0 \
  --min-competition-share 1.0 >/dev/null; then
  echo "Expected solicitation-only SAM export audit to block promotion." >&2
  exit 1
fi
grep -q "promotion-readiness,blocked" "$tmpdir/reports/sam-contract-awards-export-audit.csv"
grep -q "raw-solicitation-date-share,diagnostic,1.0000" "$tmpdir/reports/sam-contract-awards-export-audit.csv"
grep -q "use an awards/action-history export surface" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "no recognized obligation/amount field" "$tmpdir/reports/sam-contract-awards-export-audit.md"

python3 - "$tmpdir/reports/sam-contract-awards-export-audit.csv" "$tmpdir/sam-solicitation-only-export.csv" <<'PY'
import importlib.util
import os
from pathlib import Path
import sys

audit_csv = Path(sys.argv[1])
configured_export = Path(sys.argv[2])
spec = importlib.util.spec_from_file_location(
    "external_checklist",
    Path("scripts/write-external-finalization-checklist.py"),
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module.SAM_EXPORT_AUDIT_CSV = audit_csv
os.environ["SAM_CONTRACT_AWARDS_LIVE_CSV"] = str(configured_export)
try:
    row = module.sam_export_audit_row()
finally:
    os.environ.pop("SAM_CONTRACT_AWARDS_LIVE_CSV", None)
assert row["status"] == "blocked", row
assert "hardBlockers=action-date-coverage" in row["evidence"], row
assert "rawActionDate=0.0000" in row["evidence"], row
assert "rawSolicitationDate=1.0000" in row["evidence"], row
assert "rawAmount=0.0000" in row["evidence"], row
assert "Do not promote this SAM export" in row["nextAction"], row
assert "action-history export" in row["nextAction"], row
PY

cat > "$tmpdir/sam-wrapper-blocked-export.csv" <<'CSV'
contractId.piid,modification_number,recipientName,contractingDepartmentName,contractingSubtierName,awardOrIDVTypeName,Federal Action Obligation,Recipient UEI,actionDate,extentCompetedName,numberOfOffers,typeOfContractPricingName
68HERH24C9999,0,WRAPPER BLOCKED CONTRACTOR,ENVIRONMENTAL PROTECTION AGENCY,EPA OFFICE,DEFINITIVE CONTRACT,1250000,WRAPUEI1234,2024-01-15,FULL AND OPEN COMPETITION,5,FIRM FIXED PRICE
CSV
set +e
SAM_CONTRACT_AWARDS_LIVE_CSV="$tmpdir/sam-wrapper-blocked-export.csv" \
SAM_CONTRACT_AWARDS_LIVE_URL= \
SAM_CONTRACT_AWARDS_ALLOW_DIAGNOSTIC_PROMOTION=0 \
./scripts/refresh-sam-procurement-panel.sh --mode manual-export --no-artifacts >"$tmpdir/sam-wrapper.out" 2>&1
wrapper_exit="$?"
set -e
if [ "$wrapper_exit" -ne 65 ]; then
  echo "Expected guarded SAM refresh wrapper to reject a blocked export with exit 65, got $wrapper_exit." >&2
  cat "$tmpdir/sam-wrapper.out" >&2
  exit 1
fi
grep -q "Not promoting into the live snapshot" "$tmpdir/sam-wrapper.out"
grep -q "promotion-readiness,blocked" reports/sam-contract-awards-export-audit.csv
rm -f reports/sam-contract-awards-export-audit.csv reports/sam-contract-awards-export-audit.md

python3 - "$tmpdir/reports" <<'PY'
import argparse
import importlib.util
from pathlib import Path
import sys

reports = Path(sys.argv[1])
path = Path("scripts/audit-sam-contract-awards-export.py")
spec = importlib.util.spec_from_file_location("sam_export_audit", path)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
message = (
    'GET https://api.sam.gov/contract-awards/v1/download?api_key=REDACTED&token=example '
    'failed with HTTP 429: {"code":"900804","message":"Message throttled out",'
    '"description":"You have exceeded your quota .","nextAccessTime":"2026-Jun-16 00:00:00+0000 UTC"}'
)
freshness = {
    "status": "unknown",
    "evidence": "generatedAt=missing; expiresAt=missing; ttlMinutes=60",
    "generatedAt": "",
    "expiresAt": "",
    "ttlMinutes": "60",
}
rows = module.download_failure_rows(message, freshness)
assert rows[0]["status"] == "quota_blocked", rows[0]
assert rows[1]["value"] == "HTTP 429", rows[1]
assert rows[2]["item"] == "next-access-time", rows[2]
assert "2026-Jun-16 00:00:00+0000 UTC" in rows[2]["value"], rows[2]
module.write_csv(reports / "sam-contract-awards-export-audit.csv", rows)
module.write_download_failure_markdown(
    reports / "sam-contract-awards-export-audit.md",
    rows,
    argparse.Namespace(url="https://api.sam.gov/contract-awards/v1/download?api_key=REPLACE_WITH_API_KEY&token=example"),
    message,
    freshness,
)
PY
grep -q "promotion-readiness,quota_blocked" "$tmpdir/reports/sam-contract-awards-export-audit.csv"
grep -q "next-access-time,manual_required,2026-Jun-16 00:00:00+0000 UTC" "$tmpdir/reports/sam-contract-awards-export-audit.csv"
grep -q "api_key=REDACTED" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "token=REDACTED" "$tmpdir/reports/sam-contract-awards-export-audit.md"
if grep -q "token=example" "$tmpdir/reports/sam-contract-awards-export-audit.md"; then
  echo "SAM export audit report leaked an emailed download token." >&2
  exit 1
fi
grep -q "request a fresh export email" "$tmpdir/reports/sam-contract-awards-export-audit.md"

python3 - "$tmpdir/reports/sam-contract-awards-preflight.csv" <<'PY'
import csv
import importlib.util
import os
from pathlib import Path
import sys

preflight_csv = Path(sys.argv[1])
spec = importlib.util.spec_from_file_location(
    "external_checklist",
    Path("scripts/write-external-finalization-checklist.py"),
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module.SAM_PREFLIGHT_CSV = preflight_csv

row = module.sam_preflight_row()
assert row["status"] == "manual_required", row
assert "preflight=missing" in row["evidence"], row

preflight_csv.parent.mkdir(parents=True, exist_ok=True)
with preflight_csv.open("w", newline="", encoding="utf-8") as target:
    writer = csv.DictWriter(
        target,
        fieldnames=["source", "status", "rows", "nextAccessTime", "notes"],
        lineterminator="\n",
    )
    writer.writeheader()
    writer.writerow({
        "source": "sam-contract-awards",
        "status": "quota_blocked",
        "rows": "0",
        "nextAccessTime": "2026-Jun-16 00:00:00+0000 UTC",
        "notes": "SAM.gov quota blocked until 2026-Jun-16 00:00:00+0000 UTC; api_key=REDACTED",
    })
row = module.sam_preflight_row()
assert row["status"] == "manual_required", row
assert "status=quota_blocked" in row["evidence"], row
assert "2026-Jun-16 00:00:00+0000 UTC" in row["evidence"], row
assert "Wait until 2026-Jun-16 00:00:00+0000 UTC" in row["nextAction"], row

with preflight_csv.open("w", newline="", encoding="utf-8") as target:
    writer = csv.DictWriter(
        target,
        fieldnames=["source", "status", "rows", "nextAccessTime", "notes"],
        lineterminator="\n",
    )
    writer.writeheader()
    writer.writerow({
        "source": "sam-contract-awards",
        "status": "ok",
        "rows": "1",
        "nextAccessTime": "",
        "notes": "preflight agency=EPA; normalized rows returned=1",
    })
row = module.sam_preflight_row()
assert row["status"] == "ready", row
assert "rows=1" in row["evidence"], row
assert "representative settings" in row["nextAction"], row
PY

python3 - "$tmpdir/reports/sam-contract-awards-export-audit-for-input.csv" <<'PY'
import csv
import importlib.util
import os
from pathlib import Path
import sys

spec = importlib.util.spec_from_file_location(
    "external_checklist",
    Path("scripts/write-external-finalization-checklist.py"),
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
audit_csv = Path(sys.argv[1])
module.SAM_EXPORT_AUDIT_CSV = audit_csv

keys = [
    "SAM_CONTRACT_AWARDS_LIVE_URL",
    "SAM_API_KEY",
    "SAM_CONTRACT_AWARDS_LIVE_URL_GENERATED_AT",
    "SAM_CONTRACT_AWARDS_LIVE_URL_EXPIRES_AT",
    "SAM_CONTRACT_AWARDS_LIVE_URL_VALID_MINUTES",
]
saved = {key: os.environ.get(key) for key in keys}
try:
    if audit_csv.exists():
        audit_csv.unlink()
    for key in keys:
        os.environ.pop(key, None)
    os.environ["SAM_CONTRACT_AWARDS_LIVE_URL"] = "https://api.sam.gov/contract-awards/v1/download?api_key=REPLACE_WITH_API_KEY&token=fixture"
    os.environ["SAM_API_KEY"] = "fixture-key"
    row = module.sam_export_input_row()
    assert row["status"] == "manual_required", row
    assert "linkFreshness=unknown" in row["evidence"], row
    assert "token=REDACTED" in row["evidence"], row
    assert "fixture" not in row["evidence"], row
    assert "Record SAM_CONTRACT_AWARDS_LIVE_URL_GENERATED_AT" in row["nextAction"], row

    os.environ["SAM_CONTRACT_AWARDS_LIVE_URL_GENERATED_AT"] = "2099-01-01T00:00:00Z"
    os.environ["SAM_CONTRACT_AWARDS_LIVE_URL_VALID_MINUTES"] = "60"
    row = module.sam_export_input_row()
    assert row["status"] == "ready", row
    assert "linkFreshness=fresh" in row["evidence"], row
    assert "expiresAt=2099-01-01T01:00:00Z" in row["evidence"], row

    audit_csv.parent.mkdir(parents=True, exist_ok=True)
    with audit_csv.open("w", newline="", encoding="utf-8") as target:
        writer = csv.DictWriter(
            target,
            fieldnames=["item", "status", "value", "threshold", "notes", "nextAction"],
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerow({
            "item": "export-link-retry-window",
            "status": "manual_required",
            "value": "quota reset occurs after emailed token expiry",
            "threshold": "SAM reset before expiresAt",
            "notes": "generatedAt=2099-01-01T00:00:00Z; expiresAt=2099-01-01T01:00:00Z; ttlMinutes=60",
            "nextAction": "Request a fresh SAM.gov export email after the quota reset and update SAM_CONTRACT_AWARDS_LIVE_URL metadata.",
        })
    row = module.sam_export_input_row()
    assert row["status"] == "manual_required", row
    assert "retryWindow=missed" in row["evidence"], row
    assert "Wait for the SAM.gov quota reset" in row["nextAction"], row

    audit_csv.unlink()

    os.environ["SAM_CONTRACT_AWARDS_LIVE_URL_GENERATED_AT"] = "2000-01-01T00:00:00Z"
    row = module.sam_export_input_row()
    assert row["status"] == "manual_required", row
    assert "linkFreshness=expired" in row["evidence"], row
    assert "Request a fresh SAM.gov export email" in row["nextAction"], row
finally:
    for key, value in saved.items():
        if value is None:
            os.environ.pop(key, None)
        else:
            os.environ[key] = value
PY

set +e
SAM_CONTRACT_AWARDS_LIVE_URL_GENERATED_AT=2000-01-01T00:00:00Z \
SAM_CONTRACT_AWARDS_LIVE_URL_VALID_MINUTES=60 \
python3 scripts/audit-sam-contract-awards-export.py \
  --url "https://api.sam.gov/contract-awards/v1/download?api_key=REPLACE_WITH_API_KEY&token=expired-fixture" \
  --reports "$tmpdir/reports" >/dev/null
expired_audit_exit="$?"
set -e
if [ "$expired_audit_exit" -ne 1 ]; then
  echo "Expected expired SAM export URL audit to fail closed with exit 1, got $expired_audit_exit." >&2
  exit 1
fi
grep -q "promotion-readiness,manual_required,SAM.gov emailed export URL appears expired" "$tmpdir/reports/sam-contract-awards-export-audit.csv"
grep -q "export-link-freshness,manual_required,generatedAt=2000-01-01T00:00:00Z; expiresAt=2000-01-01T01:00:00Z; ttlMinutes=60" "$tmpdir/reports/sam-contract-awards-export-audit.csv"
grep -q "Link freshness: .expired." "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "api_key=REDACTED" "$tmpdir/reports/sam-contract-awards-export-audit.md"
grep -q "token=REDACTED" "$tmpdir/reports/sam-contract-awards-export-audit.md"
if grep -q "expired-fixture" "$tmpdir/reports/sam-contract-awards-export-audit.md"; then
  echo "Expired SAM export audit report leaked an emailed download token." >&2
  exit 1
fi

python3 - <<'PY'
import importlib.util
from pathlib import Path

spec = importlib.util.spec_from_file_location(
    "sam_export_audit",
    Path("scripts/audit-sam-contract-awards-export.py"),
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
message = 'GET https://api.sam.gov/contract-awards/v1/download?api_key=REDACTED&token=REDACTED failed with HTTP 429: {"code":"900804","message":"Message throttled out","description":"You have exceeded your quota .You can access API after 2026-Jun-19 00:00:00+0000 UTC","nextAccessTime":"2026-Jun-19 00:00:00+0000 UTC"}'
freshness = {
    "status": "fresh",
    "evidence": "generatedAt=2026-06-18T08:43:05Z; expiresAt=2026-06-18T09:43:05Z; ttlMinutes=60",
    "generatedAt": "2026-06-18T08:43:05Z",
    "expiresAt": "2026-06-18T09:43:05Z",
    "ttlMinutes": "60",
}
rows = module.download_failure_rows(message, freshness)
by_item = {row["item"]: row for row in rows}
assert by_item["promotion-readiness"]["status"] == "quota_blocked", rows
assert "request a fresh emailed export" in by_item["promotion-readiness"]["nextAction"], rows
assert by_item["export-link-retry-window"]["status"] == "manual_required", rows
assert "expiresAt=2026-06-18T09:43:05Z" in by_item["export-link-retry-window"]["notes"], rows
PY

python3 - "$tmpdir/reports/github-ci-status-audit.csv" <<'PY'
import csv
import importlib.util
from pathlib import Path
import sys

ci_csv = Path(sys.argv[1])
spec = importlib.util.spec_from_file_location(
    "external_checklist",
    Path("scripts/write-external-finalization-checklist.py"),
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module.GITHUB_CI_STATUS_CSV = ci_csv

row = module.github_ci_status_row()
assert row["status"] == "manual_required", row
assert "post-release CI audit=missing" in row["evidence"], row

ci_csv.parent.mkdir(parents=True, exist_ok=True)
fields = [
    "gate",
    "status",
    "workflow",
    "branchOrTag",
    "headSha",
    "runId",
    "runStatus",
    "conclusion",
    "url",
    "evidence",
    "nextAction",
]
with ci_csv.open("w", newline="", encoding="utf-8") as target:
    writer = csv.DictWriter(target, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    writer.writerow({
        "gate": "release-tag-target",
        "status": "ready",
        "workflow": "local-git",
        "branchOrTag": "paper-publication-readiness-2026-06-18-r157",
        "headSha": "abc123",
        "runId": "",
        "runStatus": "completed",
        "conclusion": "success",
        "url": "",
        "evidence": "tag points at current HEAD",
        "nextAction": "Keep the release tag on the exact commit used for the paper bundle.",
    })
    writer.writerow({
        "gate": "main-ci",
        "status": "ready",
        "workflow": "CI",
        "branchOrTag": "main",
        "headSha": "abc123",
        "runId": "111",
        "runStatus": "completed",
        "conclusion": "success",
        "url": "https://github.example/run/111",
        "evidence": "workflow=CI",
        "nextAction": "Retain this CI evidence with the release and DOI handoff records.",
    })
    writer.writerow({
        "gate": "release-tag-ci",
        "status": "ready",
        "workflow": "CI",
        "branchOrTag": "paper-publication-readiness-2026-06-18-r157",
        "headSha": "abc123",
        "runId": "112",
        "runStatus": "completed",
        "conclusion": "success",
        "url": "https://github.example/run/112",
        "evidence": "workflow=CI",
        "nextAction": "Retain this CI evidence with the release and DOI handoff records.",
    })
row = module.github_ci_status_row()
assert row["status"] == "ready", row
assert "ready=3" in row["evidence"], row
assert "main=completed/success" in row["evidence"], row
assert "tag=completed/success" in row["evidence"], row

with ci_csv.open("w", newline="", encoding="utf-8") as target:
    writer = csv.DictWriter(target, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    writer.writerow({
        "gate": "release-tag-target",
        "status": "ready",
        "workflow": "local-git",
        "branchOrTag": "paper-publication-readiness-2026-06-18-r157",
        "headSha": "abc123",
        "runId": "",
        "runStatus": "completed",
        "conclusion": "success",
        "url": "",
        "evidence": "tag points at current HEAD",
        "nextAction": "Keep the release tag on the exact commit used for the paper bundle.",
    })
    writer.writerow({
        "gate": "main-ci",
        "status": "blocked",
        "workflow": "CI",
        "branchOrTag": "main",
        "headSha": "abc123",
        "runId": "113",
        "runStatus": "completed",
        "conclusion": "failure",
        "url": "https://github.example/run/113",
        "evidence": "workflow=CI",
        "nextAction": "Inspect the failed GitHub Actions run and fix the repository before final submission.",
    })
row = module.github_ci_status_row()
assert row["status"] == "blocked", row
assert "blocked=1" in row["evidence"], row
assert "main=completed/failure" in row["evidence"], row
PY

mkdir -p "$tmpdir/doi-repo/paper/sections" "$tmpdir/doi-repo/reports"
cat > "$tmpdir/doi-repo/CITATION.cff" <<'YAML'
cff-version: 1.2.0
title: "Lobby Capture Simulator"
version: "paper-publication-readiness-2026-06-18-r157"
repository-code: "https://github.com/Jacoba1100254352/lobby-capture-simulator"
url: "https://github.com/Jacoba1100254352/lobby-capture-simulator/releases/tag/paper-publication-readiness-2026-06-18-r157"
license: MIT
preferred-citation:
  type: article
  title: "Strategic Channel Substitution in Regulatory Capture"
YAML
cat > "$tmpdir/doi-repo/.zenodo.json" <<'JSON'
{
  "title": "Lobby Capture Simulator",
  "upload_type": "software",
  "related_identifiers": [
    {
      "identifier": "https://github.com/Jacoba1100254352/lobby-capture-simulator/releases/tag/paper-publication-readiness-2026-06-18-r157",
      "relation": "isIdenticalTo",
      "resource_type": "software"
    },
    {
      "identifier": "https://doi.org/10.5281/zenodo.7654321",
      "relation": "isIdenticalTo",
      "resource_type": "software"
    }
  ]
}
JSON
cat > "$tmpdir/doi-repo/paper/sections/submission-declarations.tex" <<'TEX'
\submissionsection{Data and Code Availability}
The simulator source is publicly maintained at \url{https://github.com/Jacoba1100254352/lobby-capture-simulator}. The code is released under the MIT License, and this review bundle is associated with \href{https://github.com/Jacoba1100254352/lobby-capture-simulator/releases/tag/paper-publication-readiness-2026-06-18-r157}{release r157}. Report manifests record seed and runtime provenance.
TEX
cat > "$tmpdir/doi-repo/reports/final-human-readthrough.md" <<'MD'
# Final Human Scholarly Read-Through

status: pending
signed-off-by:
signed-off-date:
reviewed-release: paper-publication-readiness-2026-06-18-r157
reviewed-commit:
doi-archive:
MD
python3 - "$tmpdir/doi-repo" <<'PY'
import importlib.util
import os
from pathlib import Path
import sys

root = Path(sys.argv[1])
spec = importlib.util.spec_from_file_location(
    "external_checklist",
    Path("scripts/write-external-finalization-checklist.py"),
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module.CITATION = root / "CITATION.cff"
module.ZENODO = root / ".zenodo.json"
module.DECLARATIONS = root / "paper" / "sections" / "submission-declarations.tex"
module.FINAL_READTHROUGH = root / "reports" / "final-human-readthrough.md"
os.environ["ARCHIVE_DOI"] = "https://doi.org/10.5281/zenodo.1234567"
try:
    row = module.doi_record_row()
finally:
    os.environ.pop("ARCHIVE_DOI", None)
assert row["status"] == "blocked", row
assert "configuredDOI=10.5281/zenodo.1234567" in row["evidence"], row
assert "recordedDOI=10.5281/zenodo.7654321" in row["evidence"], row
assert "make record-doi-archive" in row["nextAction"], row
PY
python3 scripts/record-doi-archive.py --root "$tmpdir/doi-repo" --doi "https://doi.org/10.5281/zenodo.1234567" >/dev/null
grep -q 'doi: "10.5281/zenodo.1234567"' "$tmpdir/doi-repo/CITATION.cff"
grep -q '"doi": "10.5281/zenodo.1234567"' "$tmpdir/doi-repo/.zenodo.json"
grep -q '"identifier": "https://doi.org/10.5281/zenodo.1234567"' "$tmpdir/doi-repo/.zenodo.json"
if grep -q '10.5281/zenodo.7654321' "$tmpdir/doi-repo/.zenodo.json"; then
  echo "old DOI identifier was retained after DOI refresh" >&2
  exit 1
fi
grep -q 'DOI archive for this review bundle is \\href{https://doi.org/10.5281/zenodo.1234567}{10.5281/zenodo.1234567}' "$tmpdir/doi-repo/paper/sections/submission-declarations.tex"
grep -q '^doi-archive: https://doi.org/10.5281/zenodo.1234567$' "$tmpdir/doi-repo/reports/final-human-readthrough.md"
grep -q '^status: pending$' "$tmpdir/doi-repo/reports/final-human-readthrough.md"
python3 - "$tmpdir/doi-repo" <<'PY'
import importlib.util
import os
from pathlib import Path
import sys

root = Path(sys.argv[1])
spec = importlib.util.spec_from_file_location(
    "external_checklist",
    Path("scripts/write-external-finalization-checklist.py"),
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module.CITATION = root / "CITATION.cff"
module.ZENODO = root / ".zenodo.json"
module.DECLARATIONS = root / "paper" / "sections" / "submission-declarations.tex"
module.FINAL_READTHROUGH = root / "reports" / "final-human-readthrough.md"
os.environ["ARCHIVE_DOI"] = "10.5281/zenodo.1234567"
try:
    row = module.doi_record_row()
finally:
    os.environ.pop("ARCHIVE_DOI", None)
assert row["status"] == "ready", row
assert "DOI=present: 10.5281/zenodo.1234567" in row["evidence"], row
assert "configuredDOI=10.5281/zenodo.1234567" in row["evidence"], row
PY

python3 scripts/test-source-fetchers.py

printf 'GET https://api.sam.gov/contract-awards/v1/search?api_key=REDACTED failed with HTTP 429: {"code":"900804","message":"Message throttled out","description":"You have exceeded your quota .","nextAccessTime":"2026-Jun-13 00:00:00+0000 UTC"}\n' > "$tmpdir/sam-quota.log"
python3 scripts/classify-source-failure.py sam-contract-awards "$tmpdir/sam-quota.log" --context "mode=0" --fallback-note "fallback=USAspending action rows" > "$tmpdir/sam-quota-status.csv"
python3 - "$tmpdir/sam-quota-status.csv" <<'PY'
import csv
import sys
with open(sys.argv[1], newline="", encoding="utf-8") as source:
    rows = list(csv.DictReader(source, fieldnames=["source", "status", "notes"]))
assert rows[0]["source"] == "sam-contract-awards", rows[0]
assert rows[0]["status"] == "quota_blocked", rows[0]
assert "2026-Jun-13 00:00:00+0000 UTC" in rows[0]["notes"], rows[0]
assert "fallback=USAspending action rows" in rows[0]["notes"], rows[0]
PY

echo "Normalizer and table-generator tests passed."
